dbconnection:
  user: 'postgres'
  password: 'superuser'
  host: 'rbac-db'
  port: '5432'
  database: 'roles'
  sslmode: 'disable'

mqconnection:
  host: 'nats-streaming'
  port: '4222'
  
pubsub:
  clusterid: 'test-cluster'
  clientid: 'client-id'
  queuename: 'new-queue'
  pingsinterval: 20
  maxunsuccessfulpings: 5
